version: '3.8'

services: 
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ".data/mongo:/data"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOTUSER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOTPASS:-password}

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes: 
      - ".data/redis:/data"
    
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - "./data/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal